return {
	{
		"williamboman/mason.nvim",
		dependencies = {
			"williamboman/mason-lspconfig.nvim",
		},

		lazy = false,
		opts = {
			ensure_installed = {
				"bash-language-server",
				"black",
				"codelldb",
				"crlfmt",
				"csharp-language-server",
				"csharpier",
				"debugpy",
				"delve",
				"gofumpt",
				"goimports",
				"golines",
				"gopls",
				"jdtls",
				"json-lsp",
				"lua-language-server",
				"markdown-toc",
				"markdownlint-cli2",
				"marksman",
				"netcoredbg",
				"powershell-editor-services",
				"prettier",
				"pyright",
				"ruff",
				"rust-analyzer",
				"shellcheck",
				"shfmt",
				"sqlfluff",
				"sqlfmt",
				"stylua",
				"taplo",
				"vtsls",
				"xmlformatter",
				"yaml-language-server",
			},
		},
	},
}
