wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/lake-mountains-rocks-sunrise-daylight-scenery-illustration-3840x2160-3773.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/denis-istomin-listen-to-your-heart.jpg
    fit_mode = cover
}

