general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_out = true
}

background {
    # path = ~/Pictures/wallpapers/lake-mountains-rocks-sunrise-daylight-scenery-illustration-3840x2160-3773.png
    blur_passes = 3
    blur_size = 8
    color = rgba(1e1e2e, 0)
}

input-field {
    monitor =
    size = 60, 60 
    fail_timeout = 500
    placeholder_text =  
    outline_thickness = 8
    inner_color = 0x00000000
    outer_color = 0x00000000
    font_color = 0xffcdcdcd
    fade_on_empty = false
    halign = center
    valign = center
    capslock_color = 0xfff9e2af
    hide_input = true
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_family = JetBrainsMono Nerd Font
    font_size = 96
    shadow_passess = true
    color = 0xfff5e0dc
    position = 0, 10% 
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    font_family = JetBrainsMono Nerd Font
    font_size = 20
    color = 0x99f5c2e7
    position = 0, 20% 
    halign = center
    valign = center
}

label {
    monitor =
    text = Wpisz hasło, aby odblokować...
    font_size = 18
    color = 0x99cdcdcd
    position = 0, -10%
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] curl -s 'wttr.in/Warsaw?format=%c+%t&m'
    font_family = JetBrainsMono Nerd Font
    font_size = 24
    color = 0xfff5e0dc
    position = -5%, -5%
    halign = right
    valign = top
}

